/**
 * Demo catalog for previewing the storefront. Prices are realistic for the
 * Bangladesh market (BDT) but the products, stock, warranty terms and repair
 * price list are ILLUSTRATIVE — replace them with the shop's real data from
 * the admin app before launch.
 *
 * Images are Unsplash photos (free to use) chosen to roughly match each item.
 */

const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;

const IMAGES = {
  laptopDesk: img('1496181133206-80ce9b88a853'),
  macPurple: img('1517336714731-489689fd1ca8'),
  macKeys: img('1525547719571-a2d4ac8945e2'),
  hdd: img('1531492746076-161ca9bcad58'),
  appleKeyboard: img('1587829741301-dc798b83add3'),
  dellSide: img('1588872657578-7efd1f1555ed'),
  macDesk: img('1593642632559-0c6d3fc62b89'),
  headphonesYellow: img('1505740420928-5e560c06d30e'),
  circuit: img('1518770660439-4636190af475'),
  dellXps: img('1593642632823-8f785ba67e45'),
  mouse: img('1527864550417-7fd91fc51a46'),
  macWood: img('1541807084-5c52b6b3adef'),
  macLid: img('1611186871348-b1ce696e52c9'),
  gamingRgb: img('1603302576837-37561b2e2302'),
  imac: img('1527443224154-c4a3942d3acf'),
  headphonesWhite: img('1546435770-a3e426bf472b'),
  appleWatch: img('1579586337278-3befd40fd17a'),
  headphonesDark: img('1585298723682-7115561c51b7'),
  airpods: img('1600294037681-c80b4cb5b434'),
  macCoffee: img('1484788984921-03950022c9ef'),
  windowsColor: img('1611078489935-0cb964de46d6'),
  macAngle: img('1629131726692-1accd0c53ce0'),
  airpodsPro: img('1572569511254-d8f925fe2cbb'),
  ipad: img('1544244015-0df4b3ffc6b0'),
};

// The shop's two real branches (both in Chattogram).
const BRANCHES = [
  {
    name: 'GEC Branch',
    slug: 'gec',
    address: 'Shop 451/A, Level 4, Sanmar Ocean City, Nasirabad, Chattogram 4203',
    phone: '01886670543',
    whatsapp: '01886670543',
    sort: 0,
  },
  {
    name: 'WASA Branch',
    slug: 'wasa',
    address: 'Shop 502, Level 5, Meridian Kohinoor City, WASA, Chattogram',
    phone: '01886670543',
    whatsapp: '01886670543',
    sort: 1,
  },
];

const CATEGORIES = [
  { slug: 'laptops', name: 'Laptops', sort: 1, description: 'New and used laptops for work, study and gaming.' },
  { slug: 'accessories', name: 'Accessories', sort: 2, description: 'Mice, keyboards, chargers and storage.' },
  { slug: 'mouse-keyboard', name: 'Mouse & Keyboard', parent: 'accessories', sort: 1 },
  { slug: 'chargers-adapters', name: 'Chargers & Adapters', parent: 'accessories', sort: 2 },
  { slug: 'storage', name: 'Storage', parent: 'accessories', sort: 3 },
  { slug: 'audio', name: 'Headphones & Earbuds', sort: 3 },
  { slug: 'tablets', name: 'Tablets', sort: 4 },
  { slug: 'smart-watches', name: 'Smart Watches', sort: 5 },
  { slug: 'desktops', name: 'Desktops & All-in-One', sort: 6 },
];

const BRANDS = [
  ['Apple', 'apple'], ['Lenovo', 'lenovo'], ['Dell', 'dell'], ['HP', 'hp'], ['ASUS', 'asus'],
  ['Microsoft', 'microsoft'], ['MSI', 'msi'], ['Acer', 'acer'], ['Logitech', 'logitech'],
  ['Anker', 'anker'], ['Sony', 'sony'], ['JBL', 'jbl'], ['Western Digital', 'western-digital'],
];

const SHOP_WARRANTY_USED = {
  months: 3,
  type: 'shop',
  notes: '3 months shop warranty on motherboard, display, RAM and storage. Battery and charger: 7 days checking warranty. Physical/liquid damage not covered.',
};

// ─── Spec templates ──────────────────────────────────────────────────────
// Keyed by category slug; subcategories inherit (Used / New / MacBooks /
// Gaming all use the Laptops template). Product `specs` below are
// [field_key, value] pairs for template fields, or { label, value, group }
// for custom rows. Highlight fields (max 4) are the key specs on cards.

const f = (key, label, extra = {}) => ({ key, label, type: 'text', ...extra });
const yesNo = (key, label) => ({ key, label, type: 'boolean' });
const highlight = { highlight: true, filterable: true };

const LAPTOP_TEMPLATE = {
  groups: [
    { name: 'Processor', fields: [
      f('processor', 'Processor', highlight),
      { key: 'cpu_generation', label: 'Generation', type: 'select', filterable: true,
        options: ['7th Gen', '8th Gen', '10th Gen', '11th Gen', '12th Gen', '13th Gen', '14th Gen', 'Core Ultra',
          'Apple M1', 'Apple M1 Pro', 'Apple M2', 'Apple M3', 'Apple M4', 'Ryzen 3000', 'Ryzen 5000', 'Ryzen 7000', 'Ryzen 8000'] },
      { key: 'cpu_cores', label: 'Cores', type: 'number' },
      f('cpu_base_clock', 'Base clock'),
      f('cpu_boost_clock', 'Boost clock'),
    ] },
    { name: 'Display', fields: [
      f('display_size', 'Display size', highlight),
      f('display_resolution', 'Resolution'),
      { key: 'display_panel', label: 'Panel', type: 'select', options: ['IPS', 'OLED', 'Mini-LED', 'TN', 'VA'] },
      f('refresh_rate', 'Refresh rate'),
      yesNo('touchscreen', 'Touchscreen'),
    ] },
    { name: 'Memory & Storage', fields: [
      f('ram', 'RAM', highlight),
      { key: 'ram_type', label: 'RAM type', type: 'select',
        options: ['DDR3', 'DDR4', 'DDR5', 'LPDDR3', 'LPDDR4x', 'LPDDR5', 'LPDDR5x', 'Unified memory'] },
      f('ram_max', 'Max RAM'),
      f('storage', 'Storage', highlight),
      { key: 'storage_type', label: 'Storage type', type: 'select', options: ['NVMe SSD', 'SATA SSD', 'HDD', 'eMMC'] },
    ] },
    { name: 'Graphics', fields: [f('gpu', 'Graphics', { filterable: true }), f('vram', 'VRAM')] },
    { name: 'Keyboard & Input', fields: [yesNo('keyboard_backlit', 'Backlit keyboard'), yesNo('fingerprint', 'Fingerprint reader')] },
    { name: 'Connectivity', fields: [f('wifi', 'Wi-Fi'), f('bluetooth', 'Bluetooth'), f('ports', 'Ports')] },
    { name: 'Battery & Power', fields: [f('battery', 'Battery'), f('adapter', 'Adapter')] },
    { name: 'Physical', fields: [f('weight', 'Weight'), f('dimensions', 'Dimensions'), f('colour', 'Colour')] },
    { name: 'Software & Warranty', fields: [f('os', 'Operating system', { filterable: true }), f('warranty', 'Warranty')] },
  ],
};

const SPEC_TEMPLATES = {
  laptops: LAPTOP_TEMPLATE,
  // Mice, keyboards, chargers and storage share one small template.
  accessories: {
    groups: [
      { name: 'General', fields: [f('type', 'Type'), f('connectivity', 'Connectivity', highlight), f('compatibility', 'Compatibility')] },
      { name: 'Performance', fields: [
        f('sensor', 'Sensor'), f('output', 'Power output', { highlight: true }), f('ports', 'Ports'),
        f('capacity', 'Capacity', highlight), f('interface', 'Interface'),
      ] },
      { name: 'Power', fields: [f('battery', 'Battery', { highlight: true })] },
      { name: 'Physical', fields: [f('form_factor', 'Form factor'), f('dimensions', 'Dimensions'), f('weight', 'Weight'), f('colour', 'Colour')] },
      { name: 'Warranty', fields: [f('warranty', 'Warranty')] },
    ],
  },
  audio: {
    groups: [
      { name: 'Audio', fields: [
        { key: 'type', label: 'Type', type: 'select', options: ['Over-ear', 'On-ear', 'In-ear', 'Speaker'], ...highlight },
        f('anc', 'Noise cancelling', { highlight: true }),
        f('driver', 'Driver'),
      ] },
      { name: 'Connectivity', fields: [f('connectivity', 'Connectivity', { highlight: true }), yesNo('multipoint', 'Multipoint'), f('codecs', 'Codecs')] },
      { name: 'Battery', fields: [f('battery', 'Battery life', { highlight: true }), f('charging', 'Charging')] },
      { name: 'Physical', fields: [f('colour', 'Colour'), f('weight', 'Weight')] },
      { name: 'Warranty', fields: [f('warranty', 'Warranty')] },
    ],
  },
  tablets: {
    groups: [
      { name: 'Performance', fields: [f('chip', 'Chip', highlight), f('storage', 'Storage', highlight), f('ram', 'RAM')] },
      { name: 'Display', fields: [f('display_size', 'Display size', highlight), f('display_resolution', 'Resolution')] },
      { name: 'Connectivity', fields: [
        { key: 'connectivity', label: 'Connectivity', type: 'select', options: ['Wi-Fi', 'Wi-Fi + Cellular'], ...highlight },
        f('ports', 'Ports'),
      ] },
      { name: 'Camera', fields: [f('rear_camera', 'Rear camera'), f('front_camera', 'Front camera')] },
      { name: 'Battery', fields: [f('battery', 'Battery')] },
      { name: 'Physical', fields: [f('weight', 'Weight'), f('colour', 'Colour')] },
      { name: 'Software & Warranty', fields: [f('os', 'Operating system'), f('accessory_support', 'Pen & keyboard support'), f('warranty', 'Warranty')] },
    ],
  },
  'smart-watches': {
    groups: [
      { name: 'Display', fields: [f('case_size', 'Case size', highlight), f('display', 'Display')] },
      { name: 'Health & Fitness', fields: [f('sensors', 'Sensors'), f('water_resistance', 'Water resistance')] },
      { name: 'Connectivity', fields: [f('connectivity', 'Connectivity', highlight), f('compatibility', 'Compatibility')] },
      { name: 'Battery', fields: [f('battery', 'Battery life', { highlight: true }), f('battery_health', 'Battery health', { highlight: true })] },
      { name: 'Physical', fields: [f('material', 'Case material'), f('colour', 'Colour')] },
      { name: 'Warranty', fields: [f('warranty', 'Warranty')] },
    ],
  },
  desktops: {
    groups: [
      { name: 'Processor', fields: [f('processor', 'Processor', highlight)] },
      { name: 'Memory & Storage', fields: [f('ram', 'RAM', highlight), f('storage', 'Storage', highlight)] },
      { name: 'Display', fields: [f('display_size', 'Display size', highlight), f('display_resolution', 'Resolution')] },
      { name: 'Graphics', fields: [f('gpu', 'Graphics')] },
      { name: 'Connectivity', fields: [f('wifi', 'Wi-Fi'), f('ports', 'Ports')] },
      { name: 'In the Box', fields: [f('included', 'Included accessories')] },
      { name: 'Software & Warranty', fields: [f('os', 'Operating system'), f('warranty', 'Warranty')] },
    ],
  },
};

const LAPTOP_KEYS = LAPTOP_TEMPLATE.groups.flatMap((g) => g.fields.map((x) => x.key));

/** Laptop specs from { field_key: value } in template order (missing keys skipped). */
const laptopSpecs = (values) =>
  LAPTOP_KEYS.filter((k) => values[k] != null).map((k) => [k, String(values[k])]);

const PRODUCTS = [
  // ─── Used business laptops ────────────────────────────────────────────
  {
    name: 'Lenovo ThinkPad T480 (Used)',
    category: 'laptops', brand: 'lenovo', condition: 'used',
    grade: 'A', battery: 86, cycles: 312, accessories: 'Original Lenovo 65W charger',
    warranty: SHOP_WARRANTY_USED, featured: true, badge: 'Best Seller', sort: 1,
    short: 'Legendary ThinkPad keyboard, dual batteries and Thunderbolt 3 — the best value business laptop.',
    description: `## Why buy it\nThe T480 is the workhorse of offices worldwide: spill-resistant keyboard, MIL-STD tested build and a **hot-swappable rear battery** for all-day use.\n\n## Condition\nGrade A — light signs of use on the lid, keyboard and screen are clean. Every unit is tested for 48 hours before sale.`,
    conditionNotes: 'Minor scuffs on the lid. Screen and keyboard in excellent condition.',
    images: ['laptopDesk', 'macKeys'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-8350U', cpu_generation: '8th Gen', cpu_cores: 4, cpu_base_clock: '1.7 GHz',
      cpu_boost_clock: '3.6 GHz', display_size: '14"', display_resolution: 'Full HD (1920×1080), anti-glare', display_panel: 'IPS',
      refresh_rate: '60 Hz', touchscreen: 'No', ram: '8 GB / 16 GB', ram_type: 'DDR4',
      ram_max: '32 GB', storage: '256 GB / 512 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics 620',
      keyboard_backlit: 'Yes', fingerprint: 'Yes', wifi: 'Wi-Fi 5 (802.11ac)', bluetooth: '4.2',
      ports: 'Thunderbolt 3, 2× USB-A, HDMI, Ethernet, SD card', battery: 'Dual battery (internal + removable), up to 8 hours', adapter: '65W USB-C', weight: '1.58 kg',
      dimensions: '336.6 × 232.5 × 19.95 mm', colour: 'Black', os: 'Windows 11 Pro',
    }),
    features: ['Intel 8th Gen quad-core i5', 'Full HD IPS display', 'Dual battery, up to 8 hours', 'Backlit spill-resistant keyboard', 'Fingerprint reader'],
    variants: [
      { name: 'i5-8350U / 8GB / 256GB SSD', sku: 'TP-T480-8-256', price: 29500, compare: 33000, attrs: { RAM: '8 GB', Storage: '256 GB SSD' }, stock: 4 },
      { name: 'i5-8350U / 16GB / 512GB SSD', sku: 'TP-T480-16-512', price: 34500, compare: 38000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },
  {
    name: 'Dell Latitude 7490 (Used)',
    category: 'laptops', brand: 'dell', condition: 'used',
    grade: 'A', battery: 82, cycles: 405, accessories: 'Original Dell 65W charger',
    warranty: SHOP_WARRANTY_USED, featured: true, sort: 2,
    short: 'Slim, premium 14" Latitude with carbon-fibre lid and a sharp Full HD screen.',
    description: `## Premium business ultrabook\nCarbon-fibre lid, aluminium hinges and a comfortable backlit keyboard. Light enough to carry every day.\n\n## Tested & graded\nBattery health above 80%, all ports tested, fresh Windows 11 installation.`,
    conditionNotes: 'Very clean. Tiny mark near the touchpad.',
    images: ['dellSide', 'laptopDesk'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-8350U / i7-8650U', cpu_generation: '8th Gen', cpu_cores: 4, cpu_base_clock: '1.7 / 1.9 GHz',
      cpu_boost_clock: '3.6 / 4.2 GHz', display_size: '14"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      touchscreen: 'No', ram: '8 GB / 16 GB', ram_type: 'DDR4', ram_max: '32 GB',
      storage: '256 GB / 512 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics 620', keyboard_backlit: 'Yes',
      fingerprint: 'No', wifi: 'Wi-Fi 5 (802.11ac)', bluetooth: '4.2', ports: 'USB-C / Thunderbolt 3, 2× USB-A, HDMI, Ethernet',
      battery: '60 Wh, up to 9 hours', adapter: '65W', weight: '1.4 kg', colour: 'Black (carbon-fibre lid)',
      os: 'Windows 11 Pro',
    }),
    features: ['Core i7 quad-core', '16 GB RAM for multitasking', 'Carbon-fibre build', 'Backlit keyboard', 'Thunderbolt 3'],
    variants: [
      { name: 'i5-8350U / 8GB / 256GB SSD', sku: 'DL-7490-I5-8-256', price: 31000, attrs: { Processor: 'Core i5-8350U', RAM: '8 GB', Storage: '256 GB SSD' }, stock: 3 },
      { name: 'i7-8650U / 16GB / 512GB SSD', sku: 'DL-7490-I7-16-512', price: 37500, compare: 41000, sale: { price: 35900, days: 7 }, attrs: { Processor: 'Core i7-8650U', RAM: '16 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },
  {
    name: 'HP EliteBook 840 G6 (Used)',
    category: 'laptops', brand: 'hp', condition: 'used',
    grade: 'A', battery: 88, cycles: 254, accessories: 'HP 65W charger',
    warranty: SHOP_WARRANTY_USED, sort: 3,
    short: 'All-aluminium EliteBook with Bang & Olufsen speakers and a privacy webcam shutter.',
    description: `## Built for professionals\nAluminium chassis, bright Full HD display and B&O-tuned speakers — great for online classes and meetings.`,
    images: ['laptopDesk', 'windowsColor'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-8365U', cpu_generation: '8th Gen', cpu_cores: 4, cpu_base_clock: '1.6 GHz',
      cpu_boost_clock: '4.1 GHz', display_size: '14"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      touchscreen: 'No', ram: '8 GB / 16 GB', ram_type: 'DDR4', ram_max: '32 GB',
      storage: '256 GB / 512 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics 620', keyboard_backlit: 'Yes',
      fingerprint: 'Yes', wifi: 'Wi-Fi 5 (802.11ac)', bluetooth: '5.0', ports: 'USB-C, 2× USB-A, HDMI',
      battery: '50 Wh', adapter: '65W', weight: '1.48 kg', colour: 'Silver',
      os: 'Windows 11 Pro',
    }),
    features: ['8th Gen Core i5 vPro', 'Aluminium body', 'Bang & Olufsen audio', 'Webcam privacy shutter'],
    variants: [
      { name: 'i5-8365U / 8GB / 256GB SSD', sku: 'HP-840G6-8-256', price: 35000, attrs: { RAM: '8 GB', Storage: '256 GB SSD' }, stock: 3 },
      { name: 'i5-8365U / 16GB / 512GB SSD', sku: 'HP-840G6-16-512', price: 39500, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 8 (Used)',
    category: 'laptops', brand: 'lenovo', condition: 'used',
    grade: 'A+', battery: 91, cycles: 140, accessories: 'Original 65W USB-C charger',
    warranty: SHOP_WARRANTY_USED, featured: true, badge: 'Premium Pick', sort: 4,
    short: 'Ultralight 1.09 kg flagship ThinkPad with 10th Gen Core i7 and 16 GB RAM.',
    description: `## The executive ThinkPad\nCarbon-fibre chassis under 1.1 kg, excellent keyboard and long battery life. Grade A+ — looks almost new.`,
    images: ['macAngle', 'laptopDesk'],
    specs: laptopSpecs({
      processor: 'Intel Core i7-10610U', cpu_generation: '10th Gen', cpu_cores: 4, cpu_base_clock: '1.8 GHz',
      cpu_boost_clock: '4.9 GHz', display_size: '14"', display_resolution: 'Full HD (1920×1080), 400 nits', display_panel: 'IPS',
      touchscreen: 'No', ram: '16 GB', ram_type: 'LPDDR3', ram_max: '16 GB (soldered)',
      storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics', keyboard_backlit: 'Yes',
      fingerprint: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.0', ports: '2× Thunderbolt 3, 2× USB-A, HDMI',
      battery: '51 Wh', adapter: '65W USB-C', weight: '1.09 kg', colour: 'Black',
      os: 'Windows 11 Pro',
    }),
    features: ['Only 1.09 kg', '10th Gen Core i7', 'Thunderbolt 3 ×2', 'Grade A+ condition'],
    variants: [
      { name: 'i7-10610U / 16GB / 512GB SSD', sku: 'TP-X1C8-16-512', price: 62000, compare: 68000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'Dell Latitude 5420 (Used)',
    category: 'laptops', brand: 'dell', condition: 'used',
    grade: 'A', battery: 89, cycles: 198, accessories: 'Dell 65W USB-C charger',
    warranty: SHOP_WARRANTY_USED, sort: 5,
    short: '11th Gen Core i5 with Iris Xe graphics — modern performance at a used price.',
    description: `## 11th Gen performance\nIris Xe graphics handles light photo editing and casual games. Wi-Fi 6 and USB-C charging.`,
    images: ['dellSide'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-1145G7', cpu_generation: '11th Gen', cpu_cores: 4, cpu_base_clock: '2.6 GHz',
      cpu_boost_clock: '4.4 GHz', display_size: '14"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      touchscreen: 'No', ram: '16 GB', ram_type: 'DDR4', ram_max: '64 GB',
      storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'Intel Iris Xe', keyboard_backlit: 'Yes',
      wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.1', ports: 'Thunderbolt 4, 2× USB-A, HDMI, Ethernet', battery: '54 Wh',
      adapter: '65W USB-C', weight: '1.36 kg', os: 'Windows 11 Pro',
    }),
    features: ['11th Gen Core i5', 'Iris Xe graphics', 'Wi-Fi 6', 'Thunderbolt 4'],
    variants: [
      { name: 'i5-1145G7 / 16GB / 512GB SSD', sku: 'DL-5420-16-512', price: 47500, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },
  {
    name: 'HP EliteBook 830 G7 (Used)',
    category: 'laptops', brand: 'hp', condition: 'used',
    grade: 'B', battery: 79, cycles: 520, accessories: 'HP 65W charger',
    warranty: SHOP_WARRANTY_USED, sort: 6,
    short: 'Compact 13.3" EliteBook — Grade B cosmetic, fully tested and great value.',
    description: `## Compact & portable\n13.3" form factor that fits any bag. Grade B: visible marks on the lid and palm rest, works perfectly.`,
    conditionNotes: 'Grade B: noticeable scratches on lid and palm rest. No functional issues.',
    images: ['windowsColor'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-10310U', cpu_generation: '10th Gen', cpu_cores: 4, cpu_base_clock: '1.7 GHz',
      cpu_boost_clock: '4.4 GHz', display_size: '13.3"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      touchscreen: 'No', ram: '16 GB', ram_type: 'DDR4', ram_max: '32 GB',
      storage: '256 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics', keyboard_backlit: 'Yes',
      fingerprint: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)', ports: 'Thunderbolt 3, 2× USB-A, HDMI', adapter: '65W',
      weight: '1.28 kg', colour: 'Silver', os: 'Windows 11 Pro',
    }),
    features: ['10th Gen Core i5', '16 GB RAM', '13.3" compact size'],
    variants: [
      { name: 'i5-10310U / 16GB / 256GB SSD', sku: 'HP-830G7-16-256', price: 38500, compare: 42000, attrs: { RAM: '16 GB', Storage: '256 GB SSD' }, stock: 2 },
    ],
  },
  {
    name: 'Microsoft Surface Laptop 3 13.5" (Used)',
    category: 'laptops', brand: 'microsoft', condition: 'used',
    grade: 'A', battery: 84, cycles: 290, accessories: 'Original Surface charger',
    warranty: SHOP_WARRANTY_USED, sort: 7,
    short: 'Gorgeous 3:2 PixelSense touchscreen in a sleek aluminium body.',
    description: `## Beautiful 3:2 touchscreen\nThe tall PixelSense display is perfect for reading and writing. Alcantara-free aluminium version.`,
    images: ['macAngle'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-1035G7', cpu_generation: '10th Gen', cpu_cores: 4, cpu_base_clock: '1.2 GHz',
      cpu_boost_clock: '3.7 GHz', display_size: '13.5"', display_resolution: '2256×1504 PixelSense (3:2)', display_panel: 'IPS',
      touchscreen: 'Yes', ram: '8 GB', ram_type: 'LPDDR4x', ram_max: '8 GB (soldered)',
      storage: '256 GB', storage_type: 'NVMe SSD', gpu: 'Intel Iris Plus', keyboard_backlit: 'Yes',
      fingerprint: 'No', wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.0', ports: 'USB-C, USB-A, Surface Connect',
      battery: 'Up to 11.5 hours', adapter: '65W Surface Connect', weight: '1.29 kg', colour: 'Platinum',
      os: 'Windows 11 Home',
    }),
    features: ['3:2 PixelSense touchscreen', '10th Gen Core i5', 'Aluminium design'],
    variants: [
      { name: 'i5-1035G7 / 8GB / 256GB SSD', sku: 'MS-SL3-8-256', price: 49000, attrs: { RAM: '8 GB', Storage: '256 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'Dell XPS 13 9310 (Used)',
    category: 'laptops', brand: 'dell', condition: 'used',
    grade: 'A', battery: 87, cycles: 230, accessories: 'Dell 45W USB-C charger',
    warranty: SHOP_WARRANTY_USED, featured: true, sort: 8,
    short: 'InfinityEdge display, 11th Gen Core i7 — one of the best Windows ultrabooks.',
    description: `## Ultrabook icon\nNearly borderless 13.4" display in an aluminium and carbon-fibre body.`,
    images: ['dellXps', 'dellSide'],
    specs: laptopSpecs({
      processor: 'Intel Core i7-1185G7', cpu_generation: '11th Gen', cpu_cores: 4, cpu_base_clock: '3.0 GHz',
      cpu_boost_clock: '4.8 GHz', display_size: '13.4"', display_resolution: 'FHD+ (1920×1200) InfinityEdge', display_panel: 'IPS',
      touchscreen: 'No', ram: '16 GB', ram_type: 'LPDDR4x', ram_max: '16 GB (soldered)',
      storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'Intel Iris Xe', keyboard_backlit: 'Yes',
      fingerprint: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.1', ports: '2× Thunderbolt 4, microSD',
      battery: '52 Wh', adapter: '45W USB-C', weight: '1.2 kg', dimensions: '295.7 × 198.7 × 14.8 mm',
      colour: 'Platinum Silver', os: 'Windows 11 Home',
    }),
    features: ['11th Gen Core i7', '16:10 InfinityEdge display', 'Thunderbolt 4 ×2', 'Premium aluminium build'],
    variants: [
      { name: 'i7-1185G7 / 16GB / 512GB SSD', sku: 'DL-XPS9310-16-512', price: 79000, compare: 86000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'HP ProBook 450 G8 (Used)',
    category: 'laptops', brand: 'hp', condition: 'used',
    grade: 'A', battery: 90, cycles: 160, accessories: 'HP 65W charger',
    warranty: SHOP_WARRANTY_USED, sort: 9,
    short: '15.6" workhorse with numeric keypad — ideal for accounts and office work.',
    description: `## Big screen, full keyboard\n15.6" Full HD screen with a full-size keyboard and numeric keypad.`,
    images: ['laptopDesk'],
    specs: [
      ['processor', 'Intel Core i5-1135G7'],
      ['cpu_generation', '11th Gen'],
      ['cpu_cores', '4'],
      ['cpu_base_clock', '2.4 GHz'],
      ['cpu_boost_clock', '4.2 GHz'],
      ['display_size', '15.6"'],
      ['display_resolution', 'Full HD (1920×1080)'],
      ['display_panel', 'IPS'],
      ['ram', '8 GB'],
      ['ram_type', 'DDR4'],
      ['ram_max', '32 GB'],
      ['storage', '512 GB'],
      ['storage_type', 'NVMe SSD'],
      ['gpu', 'Intel Iris Xe'],
      ['keyboard_backlit', 'Yes'],
      ['fingerprint', 'Yes'],
      { label: 'Numeric keypad', value: 'Yes', group: 'Keyboard & Input' },
      ['wifi', 'Wi-Fi 6 (802.11ax)'],
      ['ports', 'USB-C, 2× USB-A, HDMI, Ethernet'],
      ['adapter', '65W'],
      ['weight', '1.74 kg'],
      ['colour', 'Pike Silver'],
      ['os', 'Windows 11 Pro'],
    ],
    features: ['15.6" Full HD', 'Numeric keypad', '11th Gen Core i5'],
    variants: [
      { name: 'i5-1135G7 / 8GB / 512GB SSD', sku: 'HP-450G8-8-512', price: 44000, attrs: { RAM: '8 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },

  // ─── MacBooks ─────────────────────────────────────────────────────────
  {
    name: 'Apple MacBook Air M1 13" (Used)',
    category: 'laptops', brand: 'apple', condition: 'used',
    grade: 'A', battery: 89, cycles: 187, accessories: 'Original Apple 30W USB-C charger',
    warranty: { months: 3, type: 'shop', notes: '3 months shop warranty (logic board, display, keyboard). Battery: 7 days.' },
    featured: true, badge: 'Hot Deal', sort: 10,
    short: 'Silent, fanless and fast — the M1 MacBook Air is still the best value Mac.',
    description: `## Still the value king\nApple M1 chip with up to 18 hours battery life and no fan noise.\n\n## Checked by our technicians\nBattery cycle count and health verified, iCloud/MDM free.`,
    conditionNotes: 'Clean unit, no dents. iCloud and MDM free.',
    images: ['macPurple', 'macWood', 'macLid'],
    specs: laptopSpecs({
      processor: 'Apple M1 (8-core CPU, 7-core GPU)', cpu_generation: 'Apple M1', cpu_cores: 8, display_size: '13.3"',
      display_resolution: 'Retina (2560×1600), True Tone', display_panel: 'IPS', touchscreen: 'No', ram: '8 GB',
      ram_type: 'Unified memory', ram_max: '8 GB (not upgradable)', storage: '256 GB', storage_type: 'NVMe SSD',
      gpu: 'Apple 7-core GPU', keyboard_backlit: 'Yes', fingerprint: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)',
      bluetooth: '5.0', ports: '2× Thunderbolt / USB 4', battery: 'Up to 18 hours', adapter: '30W USB-C',
      weight: '1.29 kg', colour: 'Space Grey / Gold', os: 'macOS Sequoia',
    }),
    features: ['Apple M1 chip', 'Fanless, silent design', 'Up to 18 hours battery', 'Retina display', 'iCloud/MDM free'],
    variants: [
      { name: 'M1 / 8GB / 256GB — Space Grey', sku: 'MBA-M1-8-256-SG', color: 'Space Grey', price: 68000, compare: 74000, sale: { price: 65500, days: 5 }, attrs: { Memory: '8 GB', Storage: '256 GB' }, stock: 2 },
      { name: 'M1 / 8GB / 256GB — Gold', sku: 'MBA-M1-8-256-GD', color: 'Gold', price: 68000, compare: 74000, attrs: { Memory: '8 GB', Storage: '256 GB' }, stock: 1 },
    ],
  },
  {
    name: 'Apple MacBook Pro 13" M1 (Used)',
    category: 'laptops', brand: 'apple', condition: 'used',
    grade: 'A', battery: 87, cycles: 240, accessories: 'Original Apple 61W USB-C charger',
    warranty: { months: 3, type: 'shop', notes: '3 months shop warranty. Battery: 7 days.' }, sort: 11,
    short: 'M1 performance with an active cooling fan for sustained workloads and a Touch Bar.',
    description: `## Pro performance\nActive cooling keeps the M1 at full speed for long exports and builds.`,
    images: ['macCoffee', 'macKeys'],
    specs: [
      ['processor', 'Apple M1 (8-core CPU, 8-core GPU)'],
      ['cpu_generation', 'Apple M1'],
      ['cpu_cores', '8'],
      ['display_size', '13.3"'],
      ['display_resolution', 'Retina (2560×1600), 500 nits'],
      ['display_panel', 'IPS'],
      ['ram', '8 GB / 16 GB'],
      ['ram_type', 'Unified memory'],
      ['storage', '256 GB / 512 GB'],
      ['storage_type', 'NVMe SSD'],
      ['gpu', 'Apple 8-core GPU'],
      ['keyboard_backlit', 'Yes'],
      ['fingerprint', 'Yes'],
      { label: 'Touch Bar', value: 'Yes', group: 'Keyboard & Input' },
      ['wifi', 'Wi-Fi 6 (802.11ax)'],
      ['ports', '2× Thunderbolt / USB 4'],
      ['battery', 'Up to 20 hours'],
      ['adapter', '61W USB-C'],
      ['weight', '1.4 kg'],
      ['os', 'macOS Sequoia'],
    ],
    features: ['Apple M1 with active cooling', 'Up to 20 hours battery', 'Touch Bar & Touch ID'],
    variants: [
      { name: 'M1 / 8GB / 256GB', sku: 'MBP13-M1-8-256', price: 82000, attrs: { Memory: '8 GB', Storage: '256 GB' }, stock: 1 },
      { name: 'M1 / 16GB / 512GB', sku: 'MBP13-M1-16-512', price: 99000, attrs: { Memory: '16 GB', Storage: '512 GB' }, stock: 1 },
    ],
  },
  {
    name: 'Apple MacBook Pro 14" M1 Pro (Used)',
    category: 'laptops', brand: 'apple', condition: 'used',
    grade: 'A+', battery: 93, cycles: 96, accessories: 'Original Apple 67W charger + MagSafe cable',
    warranty: { months: 3, type: 'shop', notes: '3 months shop warranty. Battery: 7 days.' }, featured: true, sort: 12,
    short: 'Liquid Retina XDR mini-LED display, MagSafe and serious M1 Pro power.',
    description: `## For creators\nM1 Pro, 120 Hz ProMotion XDR display, HDMI and SD card slot. Grade A+ with only 96 battery cycles.`,
    images: ['macLid', 'macDesk'],
    specs: laptopSpecs({
      processor: 'Apple M1 Pro (8-core CPU, 14-core GPU)', cpu_generation: 'Apple M1 Pro', cpu_cores: 8, display_size: '14.2"',
      display_resolution: 'Liquid Retina XDR (3024×1964)', display_panel: 'Mini-LED', refresh_rate: '120 Hz ProMotion', touchscreen: 'No',
      ram: '16 GB', ram_type: 'Unified memory', storage: '512 GB', storage_type: 'NVMe SSD',
      gpu: 'Apple 14-core GPU', keyboard_backlit: 'Yes', fingerprint: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)',
      bluetooth: '5.0', ports: '3× Thunderbolt 4, HDMI, SD card, MagSafe 3', battery: 'Up to 17 hours', adapter: '67W USB-C',
      weight: '1.6 kg', colour: 'Space Grey', os: 'macOS Sequoia',
    }),
    features: ['M1 Pro chip', 'XDR mini-LED display', 'MagSafe 3 charging', 'Only 96 battery cycles'],
    variants: [
      { name: 'M1 Pro / 16GB / 512GB', sku: 'MBP14-M1P-16-512', price: 158000, compare: 168000, attrs: { Memory: '16 GB', Storage: '512 GB' }, stock: 1 },
    ],
  },
  {
    name: 'Apple MacBook Air 13" M3 (New)',
    category: 'laptops', brand: 'apple', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year Apple limited warranty.' }, featured: true, badge: 'New Arrival', sort: 13,
    short: 'Brand-new M3 MacBook Air — sealed box with full Apple warranty.',
    description: `## The latest Air\nApple M3 chip, Liquid Retina display and up to 18 hours of battery life. Sealed box.`,
    images: ['macWood', 'macAngle'],
    specs: laptopSpecs({
      processor: 'Apple M3 (8-core CPU, 8-core GPU)', cpu_generation: 'Apple M3', cpu_cores: 8, display_size: '13.6"',
      display_resolution: 'Liquid Retina (2560×1664)', display_panel: 'IPS', touchscreen: 'No', ram: '8 GB / 16 GB',
      ram_type: 'Unified memory', storage: '256 GB / 512 GB', storage_type: 'NVMe SSD', gpu: 'Apple 8-core GPU',
      keyboard_backlit: 'Yes', fingerprint: 'Yes', wifi: 'Wi-Fi 6E', bluetooth: '5.3',
      ports: '2× Thunderbolt / USB 4, MagSafe 3', battery: 'Up to 18 hours', adapter: '30W USB-C', weight: '1.24 kg',
      colour: 'Midnight / Starlight', os: 'macOS Sequoia',
    }),
    features: ['Apple M3 chip', 'Sealed box', '1 year Apple warranty', 'MagSafe charging'],
    variants: [
      { name: 'M3 / 8GB / 256GB — Midnight', sku: 'MBA-M3-8-256-MN', color: 'Midnight', price: 139000, compare: 145000, attrs: { Memory: '8 GB', Storage: '256 GB' }, stock: 3 },
      { name: 'M3 / 16GB / 512GB — Starlight', sku: 'MBA-M3-16-512-SL', color: 'Starlight', price: 178000, attrs: { Memory: '16 GB', Storage: '512 GB' }, stock: 1 },
    ],
  },

  // ─── Gaming ───────────────────────────────────────────────────────────
  {
    name: 'ASUS ROG Strix G15 RTX 3060 (Used)',
    category: 'laptops', collection: 'gaming-laptops', brand: 'asus', condition: 'used',
    grade: 'A', battery: 81, cycles: 350, accessories: 'Original 240W ASUS charger',
    warranty: SHOP_WARRANTY_USED, featured: true, badge: 'Gamer Favourite', sort: 14,
    short: 'Ryzen 7 + RTX 3060 with a 144 Hz display — plays every modern game at high settings.',
    description: `## Serious gaming\nRTX 3060 (130 W) and Ryzen 7 5800H with a 144 Hz panel. Freshly cleaned with new thermal paste.`,
    images: ['gamingRgb'],
    specs: [
      ['processor', 'AMD Ryzen 7 5800H'],
      ['cpu_generation', 'Ryzen 5000'],
      ['cpu_cores', '8'],
      ['cpu_base_clock', '3.2 GHz'],
      ['cpu_boost_clock', '4.4 GHz'],
      ['display_size', '15.6"'],
      ['display_resolution', 'Full HD (1920×1080)'],
      ['display_panel', 'IPS'],
      ['refresh_rate', '144 Hz'],
      ['ram', '16 GB'],
      ['ram_type', 'DDR4'],
      ['ram_max', '32 GB'],
      ['storage', '512 GB'],
      ['storage_type', 'NVMe SSD'],
      ['gpu', 'NVIDIA GeForce RTX 3060 (130 W)'],
      ['vram', '6 GB GDDR6'],
      ['keyboard_backlit', 'Yes'],
      { label: 'Keyboard lighting', value: 'Per-key RGB', group: 'Keyboard & Input' },
      ['wifi', 'Wi-Fi 6 (802.11ax)'],
      ['bluetooth', '5.1'],
      ['ports', 'USB-C (DisplayPort), 3× USB-A, HDMI, Ethernet'],
      ['battery', '90 Wh'],
      ['adapter', '240W'],
      ['weight', '2.3 kg'],
      ['os', 'Windows 11 Home'],
    ],
    features: ['RTX 3060 6 GB', '144 Hz display', 'Per-key RGB keyboard', 'Freshly serviced cooling'],
    variants: [
      { name: 'R7-5800H / RTX 3060 / 16GB / 512GB', sku: 'ASUS-G15-3060-16-512', price: 105000, compare: 112000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'Lenovo Legion 5 RTX 3060 (Used)',
    category: 'laptops', collection: 'gaming-laptops', brand: 'lenovo', condition: 'used',
    grade: 'A', battery: 85, cycles: 280, accessories: 'Original 230W charger',
    warranty: SHOP_WARRANTY_USED, sort: 15,
    short: 'Cool, quiet and powerful — Legion 5 with RTX 3060 and a 165 Hz screen.',
    description: `## Balanced gaming\nExcellent cooling and keyboard with a fast 165 Hz panel.`,
    images: ['gamingRgb', 'windowsColor'],
    specs: laptopSpecs({
      processor: 'AMD Ryzen 5 5600H', cpu_generation: 'Ryzen 5000', cpu_cores: 6, cpu_base_clock: '3.3 GHz',
      cpu_boost_clock: '4.2 GHz', display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      refresh_rate: '165 Hz', ram: '16 GB', ram_type: 'DDR4', ram_max: '32 GB',
      storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'NVIDIA GeForce RTX 3060', vram: '6 GB GDDR6',
      keyboard_backlit: 'Yes', wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.1', ports: 'USB-C, 4× USB-A, HDMI, Ethernet',
      battery: '80 Wh', adapter: '230W', weight: '2.4 kg', colour: 'Phantom Blue',
      os: 'Windows 11 Home',
    }),
    features: ['RTX 3060 6 GB', '165 Hz display', 'Legion Coldfront cooling'],
    variants: [
      { name: 'R5-5600H / RTX 3060 / 16GB / 512GB', sku: 'LEG5-3060-16-512', price: 102000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 1 },
    ],
  },
  {
    name: 'MSI Thin GF63 12UCX RTX 2050 (New)',
    category: 'laptops', collection: 'gaming-laptops', brand: 'msi', condition: 'new',
    warranty: { months: 24, type: 'brand', notes: '2 years official MSI warranty.' }, sort: 16,
    short: 'Entry-level new gaming laptop with 12th Gen Core i5 and RTX 2050.',
    description: `## Start gaming\nLightweight gaming laptop for eSports titles and creative apps.`,
    images: ['gamingRgb'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-12450H', cpu_generation: '12th Gen', cpu_cores: 8, cpu_boost_clock: '4.4 GHz',
      display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS', refresh_rate: '144 Hz',
      ram: '8 GB', ram_type: 'DDR4', ram_max: '64 GB', storage: '512 GB',
      storage_type: 'NVMe SSD', gpu: 'NVIDIA GeForce RTX 2050', vram: '4 GB GDDR6', keyboard_backlit: 'Yes',
      wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.2', ports: 'USB-C, 3× USB-A, HDMI, Ethernet', battery: '52.4 Wh',
      adapter: '120W', weight: '1.86 kg', colour: 'Black', os: 'Windows 11 Home',
    }),
    features: ['12th Gen Core i5', 'RTX 2050', '144 Hz display', '2 years warranty'],
    variants: [
      { name: 'i5-12450H / RTX 2050 / 8GB / 512GB', sku: 'MSI-GF63-2050-8-512', price: 86000, compare: 89000, attrs: { RAM: '8 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },

  // ─── New everyday laptops ─────────────────────────────────────────────
  {
    name: 'ASUS Vivobook 15 X1504ZA Core i3 12th Gen (New)',
    category: 'laptops', brand: 'asus', condition: 'new',
    warranty: { months: 24, type: 'brand', notes: '2 years official ASUS warranty.' }, sort: 17,
    short: 'Affordable new laptop for students — 12th Gen Core i3, 8 GB RAM and 512 GB SSD.',
    description: `## Student favourite\nLight, reliable and fast enough for classes, browsing and office apps.`,
    images: ['windowsColor'],
    specs: laptopSpecs({
      processor: 'Intel Core i3-1215U', cpu_generation: '12th Gen', cpu_cores: 6, cpu_boost_clock: '4.4 GHz',
      display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', ram: '8 GB', ram_type: 'DDR4',
      ram_max: '16 GB', storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'Intel UHD Graphics',
      fingerprint: 'Yes', wifi: 'Wi-Fi 5 (802.11ac)', bluetooth: '5.0', ports: 'USB-C, 3× USB-A, HDMI',
      battery: '42 Wh', adapter: '65W', weight: '1.7 kg', colour: 'Quiet Blue',
      os: 'Windows 11 Home',
    }),
    features: ['12th Gen Core i3', '512 GB SSD', '2 years ASUS warranty'],
    variants: [
      { name: 'i3-1215U / 8GB / 512GB', sku: 'ASUS-X1504ZA-I3-8-512', price: 51500, attrs: { RAM: '8 GB', Storage: '512 GB SSD' }, stock: 4 },
    ],
  },
  {
    name: 'Lenovo IdeaPad Slim 3 Ryzen 5 (New)',
    category: 'laptops', brand: 'lenovo', condition: 'new',
    warranty: { months: 24, type: 'brand', notes: '2 years official Lenovo warranty.' }, sort: 18,
    short: 'Slim new laptop with Ryzen 5 7530U and a Full HD IPS display.',
    description: `## Everyday performance\n6-core Ryzen 5 handles multitasking with ease.`,
    images: ['laptopDesk'],
    specs: laptopSpecs({
      processor: 'AMD Ryzen 5 7530U', cpu_generation: 'Ryzen 7000', cpu_cores: 6, cpu_base_clock: '2.0 GHz',
      cpu_boost_clock: '4.5 GHz', display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS',
      ram: '8 GB', ram_type: 'DDR4', ram_max: '16 GB', storage: '512 GB',
      storage_type: 'NVMe SSD', gpu: 'AMD Radeon Graphics', wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.1',
      ports: 'USB-C, 2× USB-A, HDMI, SD card', battery: '47 Wh', adapter: '65W USB-C', weight: '1.62 kg',
      colour: 'Arctic Grey', os: 'Windows 11 Home',
    }),
    features: ['Ryzen 5 6-core', 'Full HD IPS', '2 years warranty'],
    variants: [
      { name: 'R5-7530U / 8GB / 512GB', sku: 'LEN-IPS3-R5-8-512', price: 56500, compare: 59000, sale: { price: 54900, days: 10 }, attrs: { RAM: '8 GB', Storage: '512 GB SSD' }, stock: 3 },
    ],
  },
  {
    name: 'HP 15 Core i5 13th Gen (New)',
    category: 'laptops', brand: 'hp', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year official HP warranty.' }, sort: 19,
    short: '13th Gen Core i5 with Iris Xe graphics for work and study.',
    description: `## Reliable and fast\n13th Gen Intel performance in a familiar HP design.`,
    images: ['laptopDesk'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-1334U', cpu_generation: '13th Gen', cpu_cores: 10, cpu_boost_clock: '4.6 GHz',
      display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', ram: '8 GB', ram_type: 'DDR4',
      ram_max: '16 GB', storage: '512 GB', storage_type: 'NVMe SSD', gpu: 'Intel Iris Xe',
      wifi: 'Wi-Fi 6 (802.11ax)', bluetooth: '5.3', ports: 'USB-C, 2× USB-A, HDMI', battery: '41 Wh',
      adapter: '65W', weight: '1.59 kg', colour: 'Natural Silver', os: 'Windows 11 Home',
    }),
    features: ['13th Gen Core i5', 'Iris Xe graphics', '1 year HP warranty'],
    variants: [
      { name: 'i5-1334U / 8GB / 512GB', sku: 'HP-15-I5-1334U-8-512', price: 67000, attrs: { RAM: '8 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },
  {
    name: 'Acer Aspire Lite 15 Core i5 (New)',
    category: 'laptops', brand: 'acer', condition: 'new',
    warranty: { months: 24, type: 'brand', notes: '2 years official Acer warranty.' }, sort: 20,
    short: 'Metal-body Acer with 16 GB RAM — great value for multitaskers.',
    description: `## More memory, less money\n16 GB RAM out of the box with a metal chassis.`,
    images: ['windowsColor'],
    specs: laptopSpecs({
      processor: 'Intel Core i5-1235U', cpu_generation: '12th Gen', cpu_cores: 10, cpu_boost_clock: '4.4 GHz',
      display_size: '15.6"', display_resolution: 'Full HD (1920×1080)', display_panel: 'IPS', ram: '16 GB',
      ram_type: 'DDR4', ram_max: '32 GB', storage: '512 GB', storage_type: 'NVMe SSD',
      gpu: 'Intel Iris Xe', wifi: 'Wi-Fi 6 (802.11ax)', ports: 'USB-C, 3× USB-A, HDMI, Ethernet', adapter: '65W',
      weight: '1.7 kg', colour: 'Steel Grey', os: 'Windows 11 Home',
    }),
    features: ['16 GB RAM', 'Metal body', '2 years warranty'],
    variants: [
      { name: 'i5-1235U / 16GB / 512GB', sku: 'ACER-AL15-I5-16-512', price: 61000, attrs: { RAM: '16 GB', Storage: '512 GB SSD' }, stock: 2 },
    ],
  },

  // ─── Accessories ──────────────────────────────────────────────────────
  {
    name: 'Logitech MX Master 3S Wireless Mouse',
    category: 'mouse-keyboard', brand: 'logitech', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year Logitech warranty.' }, featured: true, sort: 21,
    short: 'Quiet clicks, 8K DPI tracking on glass and MagSpeed scrolling.',
    description: `## The ultimate productivity mouse\nErgonomic shape, silent clicks and multi-device Easy-Switch.`,
    images: ['mouse'],
    specs: [
      ['type', 'Wireless mouse'],
      ['connectivity', 'Bluetooth, Logi Bolt USB receiver'],
      ['compatibility', 'Windows, macOS, Linux, iPadOS'],
      ['sensor', '8000 DPI Darkfield'],
      ['battery', 'USB-C rechargeable, up to 70 days'],
      ['weight', '141 g'],
    ],
    features: ['8K DPI any-surface tracking', 'Quiet clicks', 'MagSpeed electromagnetic wheel', 'USB-C fast charging'],
    variants: [
      { name: 'Graphite', sku: 'LOGI-MXM3S-GR', color: 'Graphite', price: 11800, compare: 12500, attrs: {}, stock: 6 },
      { name: 'Pale Grey', sku: 'LOGI-MXM3S-PG', color: 'Pale Grey', price: 11800, compare: 12500, attrs: {}, stock: 3 },
    ],
  },
  {
    name: 'Logitech M331 Silent Plus Wireless Mouse',
    category: 'mouse-keyboard', brand: 'logitech', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year Logitech warranty.' }, sort: 22,
    short: '90% less click noise — the perfect quiet mouse for office and home.',
    description: 'Comfortable right-handed shape with up to 24 months battery life.',
    images: ['mouse'],
    specs: [
      ['type', 'Wireless mouse'],
      ['connectivity', '2.4 GHz USB receiver'],
      ['sensor', '1000 DPI optical'],
      ['battery', '1× AA, up to 24 months'],
    ],
    features: ['Silent clicks', '24-month battery life'],
    variants: [{ name: 'Black', sku: 'LOGI-M331-BK', color: 'Black', price: 1550, attrs: {}, stock: 15 }],
  },
  {
    name: 'Apple Magic Keyboard',
    category: 'mouse-keyboard', brand: 'apple', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year Apple warranty.' }, sort: 23,
    short: 'Wireless, rechargeable Apple keyboard with a low-profile scissor mechanism.',
    description: 'Pairs automatically with your Mac. Lightning/USB-C charging cable included.',
    images: ['appleKeyboard'],
    specs: [
      ['type', 'Wireless keyboard'],
      ['connectivity', 'Bluetooth'],
      ['compatibility', 'macOS, iPadOS'],
      ['battery', 'Rechargeable, about 1 month per charge'],
      ['colour', 'White'],
    ],
    features: ['Low-profile keys', 'Rechargeable battery'],
    variants: [{ name: 'US English', sku: 'APL-MK-US', price: 10500, attrs: {}, stock: 3 }],
  },
  {
    name: 'Anker 735 Nano II 65W GaN USB-C Charger',
    category: 'chargers-adapters', brand: 'anker', condition: 'new',
    warranty: { months: 18, type: 'brand', notes: '18 months Anker warranty.' }, sort: 24,
    short: 'Charge a laptop, phone and earbuds at once from one compact charger.',
    description: 'GaN II technology, 2× USB-C + 1× USB-A. Charges MacBook Air at full speed.',
    images: ['laptopDesk'],
    specs: [
      ['type', 'GaN wall charger'],
      ['output', '65W max (USB-C)'],
      ['ports', '2× USB-C, 1× USB-A'],
      { label: 'Plug', value: 'US (BD adapter included)', group: 'General' },
    ],
    features: ['65W laptop fast charging', '3 ports', 'Compact GaN design'],
    variants: [{ name: 'Black', sku: 'ANK-735-65W', price: 4500, attrs: {}, stock: 8 }],
  },
  {
    name: 'WD Blue 1TB 2.5" Laptop Hard Drive',
    category: 'storage', brand: 'western-digital', condition: 'new',
    warranty: { months: 24, type: 'brand', notes: '2 years WD warranty.' }, sort: 25,
    short: 'Extra storage for older laptops or as a backup drive.',
    description: '5400 RPM SATA laptop hard drive. Pair with a USB caddy for external backup.',
    images: ['hdd'],
    specs: [
      ['type', 'Internal hard drive'],
      ['capacity', '1 TB'],
      ['interface', 'SATA 6 Gb/s'],
      { label: 'Spindle speed', value: '5400 RPM', group: 'Performance' },
      ['form_factor', '2.5", 7 mm'],
    ],
    features: ['1 TB capacity', '2 years warranty'],
    variants: [{ name: '1 TB', sku: 'WD-BLUE-1TB-25', price: 4600, attrs: {}, stock: 5 }],
  },

  // ─── Audio, tablets, watches, desktops ────────────────────────────────
  {
    name: 'Sony WH-1000XM4 Noise Cancelling Headphones (Used)',
    category: 'audio', brand: 'sony', condition: 'used', grade: 'A',
    warranty: { months: 1, type: 'shop', notes: '1 month shop warranty.' }, sort: 26,
    short: 'Industry-leading noise cancellation, 30-hour battery — Grade A used.',
    description: 'Ear pads replaced with genuine Sony pads. Comes with case and cable.',
    images: ['headphonesWhite', 'headphonesDark'],
    accessories: 'Carry case, USB-C cable, 3.5 mm cable',
    specs: [
      ['type', 'Over-ear'],
      ['anc', 'Yes, adaptive'],
      ['driver', '40 mm'],
      ['connectivity', 'Bluetooth 5.0, 3.5 mm cable'],
      ['multipoint', 'Yes'],
      ['codecs', 'LDAC, AAC, SBC'],
      ['battery', 'Up to 30 hours'],
      ['charging', 'USB-C, 10 min for 5 hours'],
      ['colour', 'Black'],
      ['weight', '254 g'],
    ],
    features: ['Adaptive noise cancelling', '30-hour battery', 'New genuine ear pads'],
    variants: [{ name: 'Black', sku: 'SONY-XM4-BK-U', color: 'Black', price: 24500, compare: 27000, attrs: {}, stock: 1 }],
  },
  {
    name: 'JBL Tune 520BT Wireless Headphones',
    category: 'audio', brand: 'jbl', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year JBL warranty.' }, sort: 27,
    short: 'JBL Pure Bass sound with up to 57 hours of playback.',
    description: 'Lightweight on-ear headphones with multipoint connection.',
    images: ['headphonesYellow'],
    specs: [
      ['type', 'On-ear'],
      ['anc', 'No'],
      ['driver', '33 mm'],
      ['connectivity', 'Bluetooth 5.3'],
      ['multipoint', 'Yes'],
      ['battery', 'Up to 57 hours'],
      ['charging', 'USB-C'],
      ['colour', 'Black'],
    ],
    features: ['57-hour battery', 'Multipoint Bluetooth'],
    variants: [{ name: 'Black', sku: 'JBL-T520BT-BK', color: 'Black', price: 5200, attrs: {}, stock: 6 }],
  },
  {
    name: 'Apple AirPods Pro (2nd generation) USB-C',
    category: 'audio', brand: 'apple', condition: 'new',
    warranty: { months: 12, type: 'brand', notes: '1 year Apple warranty.' }, featured: true, sort: 28,
    short: 'Active noise cancellation, Adaptive Audio and a USB-C MagSafe case.',
    description: 'Up to 2× more noise cancellation than the original AirPods Pro.',
    images: ['airpodsPro', 'airpods'],
    specs: [
      ['type', 'In-ear'],
      ['anc', 'Active + Adaptive Audio'],
      ['connectivity', 'Bluetooth 5.3'],
      ['battery', 'Up to 6 hours (30 hours with case)'],
      ['charging', 'MagSafe case, USB-C'],
      ['colour', 'White'],
    ],
    features: ['Active noise cancellation', 'Adaptive Audio', 'USB-C MagSafe case'],
    variants: [{ name: 'White', sku: 'APL-APP2-USBC', price: 28500, compare: 31000, sale: { price: 27500, days: 7 }, attrs: {}, stock: 4 }],
  },
  {
    name: 'Apple iPad 9th Gen 10.2" Wi-Fi (Used)',
    category: 'tablets', brand: 'apple', condition: 'used', grade: 'A', battery: 92,
    warranty: { months: 1, type: 'shop', notes: '1 month shop warranty.' }, sort: 29,
    short: 'Perfect for online classes, reading and Netflix — iCloud free.',
    description: 'Grade A screen, original charger included.',
    accessories: 'Original 20W charger and cable',
    images: ['ipad'],
    specs: [
      ['chip', 'A13 Bionic'],
      ['storage', '64 GB'],
      ['ram', '3 GB'],
      ['display_size', '10.2"'],
      ['display_resolution', 'Retina (2160×1620)'],
      ['connectivity', 'Wi-Fi'],
      ['ports', 'Lightning'],
      ['rear_camera', '8 MP'],
      ['front_camera', '12 MP Ultra Wide, Center Stage'],
      ['battery', 'Up to 10 hours'],
      ['weight', '487 g'],
      ['colour', 'Space Grey'],
      ['os', 'iPadOS'],
      ['accessory_support', 'Apple Pencil (1st gen), Smart Keyboard'],
    ],
    features: ['A13 Bionic chip', 'Apple Pencil (1st gen) support', 'iCloud free'],
    variants: [{ name: '64 GB — Space Grey', sku: 'IPAD9-64-SG-U', color: 'Space Grey', price: 29500, attrs: { Storage: '64 GB' }, stock: 1 }],
  },
  {
    name: 'Apple Watch Series 7 45mm GPS (Used)',
    category: 'smart-watches', brand: 'apple', condition: 'used', grade: 'A', battery: 88,
    warranty: { months: 1, type: 'shop', notes: '1 month shop warranty.' }, sort: 30,
    short: 'Larger always-on display, fast charging and full health tracking.',
    description: 'Comes with charger and a new sport band.',
    images: ['appleWatch'],
    specs: [
      ['case_size', '45 mm'],
      ['display', 'Always-On Retina'],
      ['sensors', 'ECG, blood oxygen, heart rate'],
      ['water_resistance', 'WR50 (swim-proof)'],
      ['connectivity', 'GPS'],
      ['compatibility', 'iPhone only'],
      ['battery', 'Up to 18 hours'],
      ['battery_health', '88%'],
      ['material', 'Aluminium'],
      ['colour', 'Midnight'],
    ],
    features: ['Always-on Retina display', 'ECG & blood oxygen apps', 'Fast charging'],
    variants: [{ name: 'Midnight Aluminium', sku: 'AW7-45-MN-U', color: 'Midnight', price: 29000, attrs: {}, stock: 1 }],
  },
  {
    name: 'Apple iMac 24" M1 (Used)',
    category: 'desktops', brand: 'apple', condition: 'used', grade: 'A',
    warranty: { months: 3, type: 'shop', notes: '3 months shop warranty.' }, sort: 31,
    short: 'Stunning 4.5K Retina all-in-one with Magic Keyboard and Mouse.',
    description: 'Complete set with original keyboard, mouse and power cable.',
    accessories: 'Magic Keyboard, Magic Mouse, power cable',
    images: ['imac', 'macDesk'],
    specs: [
      ['processor', 'Apple M1 (8-core CPU, 7-core GPU)'],
      ['ram', '8 GB'],
      ['storage', '256 GB SSD'],
      ['display_size', '24"'],
      ['display_resolution', '4.5K Retina (4480×2520)'],
      ['gpu', 'Apple 7-core GPU'],
      ['wifi', 'Wi-Fi 6 (802.11ax)'],
      ['ports', '2× Thunderbolt / USB 4'],
      ['included', 'Magic Keyboard, Magic Mouse, power cable'],
      ['os', 'macOS Sequoia'],
    ],
    features: ['4.5K Retina display', '1080p camera, studio mics', 'Complete set'],
    variants: [{ name: 'M1 / 8GB / 256GB — Silver', sku: 'IMAC24-M1-8-256-U', color: 'Silver', price: 115000, attrs: { Memory: '8 GB', Storage: '256 GB' }, stock: 1 }],
  },
];

const REPAIR_SERVICES = [
  ['Laptop Diagnostic', 'Full hardware and software check with a written report.', 500],
  ['Windows / macOS Installation', 'Clean OS installation with drivers and essential software.', 800],
  ['Cleaning & Thermal Paste', 'Internal dust cleaning and premium thermal paste to stop overheating.', 1200],
  ['SSD / RAM Upgrade (Installation)', 'Installation and data migration. Parts charged separately.', 500],
  ['Battery Replacement', 'Replacement with a quality or original battery. Price depends on model.', 3500],
  ['Display Replacement', 'Cracked or dead screen replacement. Price depends on model.', 6500],
  ['Keyboard Replacement', 'Replacement of faulty or liquid-damaged keyboards.', 2500],
  ['Charging Port / DC Jack Repair', 'Fix loose or broken charging ports.', 1800],
  ['Motherboard Repair', 'Chip-level repair for power, display and no-boot faults.', 4500],
  ['Data Recovery', 'Recover files from failed or formatted drives.', 2000],
];

// ─── Homepage banners ────────────────────────────────────────────────────
// Product slides take their title, image and live price from the product
// (by name, above); custom slides carry their own content.
const BANNERS = [
  { placement: 'hero', product: 'Apple MacBook Air M1 13" (Used)', badge: 'Hot Deal' },
  { placement: 'hero', product: 'ASUS ROG Strix G15 RTX 3060 (Used)', badge: 'Gamer Favourite' },
  {
    placement: 'hero', product: 'Dell XPS 13 9310 (Used)', badge: 'Premium Pick',
    subtitle: '11th Gen Core i7, 16 GB RAM and a near-borderless 13.4" display — Grade A with 3 months warranty.',
  },
  {
    placement: 'hero',
    title: 'Expert laptop repairs in Chattogram',
    subtitle: 'Chip-level motherboard repair, screen and battery replacement, cleaning and upgrades by experienced technicians.',
    badge: 'Repairs',
    image: 'circuit',
    cta: 'Book a repair',
    link: '/repairs',
  },
  {
    placement: 'promo',
    title: 'Used ThinkPads from ৳29,500',
    subtitle: 'Tested for 48 hours, honestly graded, with 3 months shop warranty.',
    image: 'laptopDesk',
    cta: 'Shop used laptops',
    link: '/categories/laptops?condition=used',
  },
  {
    placement: 'promo',
    title: 'Upgrade to an SSD',
    subtitle: 'Boot in seconds. SSD and RAM installation from ৳500 at our GEC and WASA branches.',
    badge: 'Service',
    image: 'hdd',
    cta: 'See repair prices',
    link: '/repairs',
  },
];

module.exports = { IMAGES, BRANCHES, CATEGORIES, BRANDS, PRODUCTS, REPAIR_SERVICES, SPEC_TEMPLATES, BANNERS };
